<a href="https://colab.research.google.com/github/dongocthao261005-web/DeepLearning/blob/main/DoNgocThao_2001230903_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 1

## Array 1 chiều

In [ ]:
import numpy as np
#Tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]

In [ ]:
#Cách 2
a = np.array([1, 9, 15, 39])
print(a)

[ 1  9 15 39]

## Array 2 chiều

In [ ]:
c = np.array([(1, 2, 3),
              (4, 5, 6)
              ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64

## Bài 1

In [ ]:
import numpy as np
random_array = np.random.randint(0, 21, size=(3, 3))
print(random_array)

ktra = np.all(random_array)

print("\nTất cả các phần tử trong mảng khác 0:", ktra)

Mảng ngẫu nhiên:
[[13 18  2]
 [ 8  9 18]
 [11 18 12]]

Tất cả các phần tử trong mảng khác 0: True

## Bài 2

In [ ]:
import numpy as np
rd_array = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên:")
print(rd_array)

kiemtra = np.any(rd_array)

print("\nCó một phần tử trong mảng khác 0:", kiemtra)

Mảng ngẫu nhiên:
[[16  3 15]
 [16  4  9]
 [20 14  8]]

Có một phần tử trong mảng khác 0: True

## Bài 3

### So sánh mảng 1 chiều với các hàm NumPy

In [ ]:
import numpy as np
arr1_1c = np.array([10, 20, 30, 40, 50])
arr2_1c = np.array([5, 20, 35, 40, 45])

print("Mảng 1 chiều thứ nhất:", arr1_1c)
print("Mảng 1 chiều thứ hai:", arr2_1c)

#numpy.greater
print("\narr1_1c > arr2_1c:", np.greater(arr1_1c, arr2_1c))

#numpy.greater_equal
print("arr1_1c >= arr2_1c:", np.greater_equal(arr1_1c, arr2_1c))

#numpy.less
print("arr1_1c < arr2_1c:", np.less(arr1_1c, arr2_1c))

#numpy.less_equal
print("arr1_1c <= arr2_1c:", np.less_equal(arr1_1c, arr2_1c))

Mảng 1 chiều thứ nhất: [10 20 30 40 50]
Mảng 1 chiều thứ hai: [ 5 20 35 40 45]

arr1_1c > arr2_1c: [ True False False False  True]
arr1_1c >= arr2_1c: [ True  True False  True  True]
arr1_1c < arr2_1c: [False False  True False False]
arr1_1c <= arr2_1c: [False  True  True  True False]

### So sánh mảng 2 chiều với các hàm NumPy

In [ ]:
import numpy as np

arr1_2d = np.array([[1, 2, 3],
                    [4, 5, 6]])
arr2_2d = np.array([[0, 2, 4],
                    [3, 5, 7]])

print("Mảng 2 chiều thứ nhất:")
print(arr1_2d)
print("\nMảng 2 chiều thứ hai:")
print(arr2_2d)

#numpy.greater
print("\narr1_2d > arr2_2d:")
print(np.greater(arr1_2d, arr2_2d))

#numpy.greater_equal
print("\narr1_2d >= arr2_2d:")
print(np.greater_equal(arr1_2d, arr2_2d))

#numpy.less
print("\narr1_2d < arr2_2d:")
print(np.less(arr1_2d, arr2_2d))

#numpy.less_equal
print("\narr1_2d <= arr2_2d:")
print(np.less_equal(arr1_2d, arr2_2d))

Mảng 2 chiều thứ nhất:
[[1 2 3]
 [4 5 6]]

Mảng 2 chiều thứ hai:
[[0 2 4]
 [3 5 7]]

arr1_2d > arr2_2d:
[[ True False False]
 [ True False False]]

arr1_2d >= arr2_2d:
[[ True  True False]
 [ True  True False]]

arr1_2d < arr2_2d:
[[False False  True]
 [False False  True]]

arr1_2d <= arr2_2d:
[[False  True  True]
 [False  True  True]]

## Bài 4

In [ ]:
import numpy as np
#10 số 1
ones_array = np.ones(10, dtype=int)
#10 số 0
zeros_array = np.zeros(10, dtype=int)
#10 số 5
fives_array = np.full(10, 5, dtype=int)

combined_array = np.concatenate((ones_array, zeros_array, fives_array))
print(combined_array)

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]

## Bài 5

In [ ]:
import numpy as np
even_numbers_array = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(even_numbers_array)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

## Bài 6

In [ ]:
import numpy as np
identity_matrix = np.identity(3, dtype=int)

print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

## Bài 7

In [ ]:
import numpy as np
random_array_10_elements = np.random.randint(15, 56, size=10)
print(random_array_10_elements)

print("Các giá trị ngoại trừ phần tử đầu và cuối:", random_array_10_elements[1:-1])

[52 34 47 45 38 36 30 34 15 47]
Các giá trị ngoại trừ phần tử đầu và cuối: [34 47 45 38 36 30 34 15]

## Bài 8

In [ ]:
import numpy as np
original_array = np.random.randint(0, 21, size=20)
print("Mảng gốc:", original_array)

condition_mask = (original_array >= 9) & (original_array <= 15)

modified_array = original_array.copy()
modified_array[condition_mask] *= -1

print("Đổi dấu các số trong khoảng [9, 15]:", modified_array)

Mảng gốc: [15 10  0  9 10  7 18  1  0 10  8  2 16  3 13 17 15 13  5 11]
Đổi dấu các số trong khoảng [9, 15]: [-15 -10   0  -9 -10   7  18   1   0 -10   8   2  16   3 -13  17 -15 -13
   5 -11]

## Bài 9

In [ ]:
import numpy as np
matrix_3x4 = np.random.randint(10, 22, size=(3, 4))
print(matrix_3x4)

[[10 20 17 13]
 [18 18 21 10]
 [21 20 10 21]]

## Bài 10

In [11]:
import numpy as np
matrix_10x10 = np.zeros((10, 10), dtype=int)

matrix_10x10[0, :] = 1
matrix_10x10[-1, :] = 1
matrix_10x10[:, 0] = 1
matrix_10x10[:, -1] = 1
print(matrix_10x10)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]

## Bài 11

In [ ]:
import numpy as np
diagonal_elements = [1, 2, 3, 4, 5]
matrix = np.diag(diagonal_elements)
print(matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

## Bài 12

In [ ]:
import numpy as np
random_3d_array = np.random.randint(0, 10, size=(3, 3, 3))
print("Mảng 3x3x3 ngẫu nhiên:")
print(random_3d_array)

sum_along_columns = np.sum(random_3d_array, axis=2)
print("\nTổng theo mỗi cột (axis=2 - tổng các phần tử trên hàng ngang trong mỗi 'lớp'):")
print(sum_along_columns)

sum_along_rows = np.sum(random_3d_array, axis=1)
print("\nTổng theo mỗi dòng (axis=1 - tổng các phần tử trên hàng dọc trong mỗi 'lớp'):")
print(sum_along_rows)

sum_per_2d_slice = np.sum(random_3d_array, axis=(1, 2))
print("\nTổng các phần tử trong mỗi 'lớp' 2D:")
print(sum_per_2d_slice)

total_sum = np.sum(random_3d_array)
print("\nTổng tất cả các phần tử trong mảng 3D:")
print(total_sum)

Mảng 3x3x3 ngẫu nhiên:
[[[0 6 5]
  [4 0 1]
  [2 9 9]]

 [[5 2 1]
  [5 7 9]
  [7 4 4]]

 [[2 6 3]
  [7 4 3]
  [9 5 1]]]

Tổng theo mỗi cột (axis=2 - tổng các phần tử trên hàng ngang trong mỗi 'lớp'):
[[11  5 20]
 [ 8 21 15]
 [11 14 15]]

Tổng theo mỗi dòng (axis=1 - tổng các phần tử trên hàng dọc trong mỗi 'lớp'):
[[ 6 15 15]
 [17 13 14]
 [18 15  7]]

Tổng các phần tử trong mỗi 'lớp' 2D:
[36 44 40]

Tổng tất cả các phần tử trong mảng 3D:
120

## Bài 13

In [ ]:
import numpy as np
vector1 = np.random.rand(10)
vector2 = np.random.rand(10)

print("Vector 1:")
print(vector1)
print("\nVector 2:")
print(vector2)

inner_product = np.dot(vector1, vector2)

print(inner_product)

Vector 1:
[5.12965676e-01 6.90055620e-01 1.76814464e-01 6.69596099e-01
 3.54648779e-01 3.76040107e-01 7.37183058e-01 7.88436011e-01
 8.12625467e-05 4.77817883e-01]

Vector 2:
[0.21130225 0.51041146 0.43329007 0.02390914 0.64823058 0.91854936
 0.62607062 0.61378521 0.26784786 0.29509451]
2.215012322448402

## Bài 14

In [ ]:
import numpy as np
A = np.random.rand(4, 3)
print("Ma trận A:")
print(A)

y = np.random.rand(3)
print("\nVector y:")
print(y)

result_matrix = A + y
print("\nCộng thêm vector y vào mỗi dòng:")
print(result_matrix)

Ma trận A:
[[0.47206612 0.29412779 0.48778613]
 [0.60469524 0.87798883 0.06602039]
 [0.88463808 0.03118587 0.92575982]
 [0.56930052 0.06047553 0.02890133]]

Vector y:
[0.49311029 0.68996434 0.61308266]

Cộng thêm vector y vào mỗi dòng:
[[0.96517641 0.98409213 1.10086879]
 [1.09780553 1.56795316 0.67910305]
 [1.37774837 0.72115021 1.53884248]
 [1.06241081 0.75043987 0.64198399]]

## Bài 15

In [ ]:
import pandas as pd

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:\n", s1)
print("Series 2:\n", s2)

print("\nCộng:\n", s1 + s2)
print("\nTrừ:\n", s1 - s2)
print("\nNhân:\n", s1 * s2)
print("\nChia:\n", s1 / s2)

Series 1:
 0     2
1     4
2     6
3     8
4    10
dtype: int64
Series 2:
 0     1
1     3
2     5
3     7
4    10
dtype: int64

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64

Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

## Bài 16

In [ ]:
import pandas as pd
data = {
    'Cột 1': [10, 20, 30, 40, 50],
    'Cột 2': [5, 15, 25, 35, 45],
    'Cột 3': [1, 2, 3, 4, 5]
}
df = pd.DataFrame(data)
print("DataFrame ban đầu:")
display(df)

first_col_series = df.iloc[:, 0]

print("\nCột đầu tiên sau khi chuyển thành Series:")
print(first_col_series)
print("Kiểu dữ liệu:", type(first_col_series))

DataFrame ban đầu:

   Cột 1  Cột 2  Cột 3
0     10      5      1
1     20     15      2
2     30     25      3
3     40     35      4
4     50     45      5

Cột đầu tiên sau khi chuyển thành Series:
0    10
1    20
2    30
3    40
4    50
Name: Cột 1, dtype: int64
Kiểu dữ liệu: <class 'pandas.core.series.Series'>

## Bài 17

In [ ]:
import pandas as pd
import numpy as np

df_random = pd.DataFrame(np.random.randint(0, 100, size=(4, 3)), columns=['Cột 1', 'Cột 2', 'Cột 3'])
print("DataFrame ngẫu nhiên ban đầu:")
display(df_random)

df_sorted = df_random.sort_values(by='Cột 1')

print("\nDataFrame sau khi sắp xếp theo 'Cột 1':")
display(df_sorted)

DataFrame ngẫu nhiên ban đầu:

   Cột 1  Cột 2  Cột 3
0     75     88     53
1      9     47     55
2     98      1     35
3     36     96     11

DataFrame sau khi sắp xếp theo 'Cột 1':

   Cột 1  Cột 2  Cột 3
1      9     47     55
3     36     96     11
0     75     88     53
2     98      1     35

## Bài 18

In [ ]:
import pandas as pd

s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print("Series ban đầu:")
print(s)

new_index = ['c', 'a', 'b', 'd']
s_reindexed = s.reindex(new_index)

print("\nSeries sau khi reindex:")
print(s_reindexed)

Series ban đầu:
a    10
b    20
c    30
dtype: int64

Series sau khi reindex:
c    30.0
a    10.0
b    20.0
d     NaN
dtype: float64

## Bài 19

In [ ]:
import pandas as pd

sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("sr1:")
print(sr1)
print("\nsr2:")
print(sr2)

result = sr1[~sr1.isin(sr2)]

print("\nItems of sr1 not present in sr2:")
print(result)

sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64

sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64

## Bài 20

In [ ]:
import numpy as np
import pandas as pd

sr_x = pd.Series(np.random.randint(1, 30, 20))
sr_y = pd.Series(np.random.randint(1, 30, 20))

print("Series x:")
print(sr_x.values)
print("\nSeries y:")
print(sr_y.values)

intersection = np.intersect1d(sr_x, sr_y)
print("\nGiao của x và y (Phần tử chung):")
print(intersection)

union = np.union1d(sr_x, sr_y)
print("\nHội của x và y (Tất cả phần tử duy nhất):")
print(union)

Series x:
[23 22  6 29 20 14 24  8  5 28 10 24  4 17  3 10 20 12  7 25]

Series y:
[13 14 10 18 23  6  4  2 26 24  8 11 21 29 27 15 13  1 13  8]

Giao của x và y (Phần tử chung):
[ 4  6  8 10 14 23 24 29]

Hội của x và y (Tất cả phần tử duy nhất):
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 17 18 20 21 22 23 24 25 26 27
 28 29]

## Bài 21

In [12]:
import pandas as pd

x = pd.Series([i for i in range(10)], name='Series x')
y = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'], name='Series y')

print("Series x:")
print(x)
print("\nSeries y:")
print(y)

vertical_concat = pd.concat([x, y], axis=0)
print("\nKết hợp theo chiều dọc:")
print(vertical_concat)

horizontal_concat = pd.concat([x, y], axis=1)
print("\nKết hợp theo chiều ngang:")
display(horizontal_concat)

Series x:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Series x, dtype: int64

Series y:
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
Name: Series y, dtype: object

Kết hợp theo chiều dọc:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Kết hợp theo chiều ngang:

   Series x Series y
0         0        p
1         1        q
2         2        r
3         3        s
4         4        t
5         5        u
6         6        v
7         7        w
8         8        x
9         9        y

## Bài 22

In [1]:
import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

## Bài 23

In [2]:
print("3 dòng đầu tiên của DataFrame:")
print(df.head(3))

3 dòng đầu tiên của DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

## Bài 24

In [3]:
print("Chọn cột 'name' và 'score' từ DataFrame:")
selected_columns = df[['name', 'score']]
display(selected_columns)

Chọn cột 'name' và 'score' từ DataFrame:

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

## Bài 25

In [4]:
print("Chọn những dòng có 'attempts' > 2:")
selected_rows = df[df['attempts'] > 2]
display(selected_rows)

Chọn những dòng có 'attempts' > 2:

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

## Bài 26

In [5]:
print("Số dòng và số cột của DataFrame:")
print(df.shape)
print(f"Số dòng: {df.shape[0]}, Số cột: {df.shape[1]}")

Số dòng và số cột của DataFrame:
(10, 4)
Số dòng: 10, Số cột: 4

## Bài 27

In [6]:
print("Các dòng có score là NaN:")
display(df[df['score'].isnull()])

Các dòng có score là NaN:

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

## Bài 28

In [7]:
print("Các dòng có score trong khoảng (15, 20):")
display(df[df['score'].between(15, 20, inclusive='neither')])

Các dòng có score trong khoảng (15, 20):

        name  score  attempts qualify
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes

## Bài 29

In [8]:
print("Các dòng có attempts > 2 và score trong khoảng (15, 20):")
display(df[(df['attempts'] > 2) & (df['score'].between(15, 20, inclusive='neither'))])

Các dòng có attempts > 2 và score trong khoảng (15, 20):

Empty DataFrame
Columns: [name, score, attempts, qualify]
Index: []

## Bài 30

In [9]:
print("Thay đổi giá trị dòng 'd', cột score là 19:")
df.loc['d', 'score'] = 19
display(df)

Thay đổi giá trị dòng 'd', cột score là 19:

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes